CREATE DATABASE lessen1;

SELECT * FROM `Student` WHERE sID = 1;
CREATE TABLE Student(
#编号、姓名、年龄、姓别三个字
	sID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	sName VARCHAR(50) NOT NULL,
	sAge INT NOT NULL,
	sSex VARCHAR(2) NOT NULL
) 
INSERT INTO Student VALUES(NULL,'寜',12,'女');
UPDATE Student SET sName = '小寜' WHERE sID = 4;
DELETE FROM Student WHERE sSex = '女';
CREATE TABLE USER(
#有编号，姓名，密码，money 
	uID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	uName VARCHAR(50) NOT NULL,
	uPassword VARCHAR(14) NOT NULL,
	uMoney FLOAT NOT NULL 
)
INSERT INTO USER VALUES(NULL,'寜','1008611',200);
INSERT INTO USER VALUES(NULL,'寜','1008611',200.1);
DELETE FROM USER WHERE uID = 1;
UPDATE USER SET uName = '小寜' WHERE uID = 3;
SELECT * FROM USER;